const DEFAULT_BET = 100;
const INCREASE_BET_BY = 100;
const DECREASE_BET_BY = 100;
const HISTORY_ID_LENGTH = 5;
const COINS_PER_RETREAT = 100;
const DECREASE_SELL_PRICE_BY = 90;

export {
  DEFAULT_BET,
  INCREASE_BET_BY,
  DECREASE_BET_BY,
  HISTORY_ID_LENGTH,
  COINS_PER_RETREAT,
  DECREASE_SELL_PRICE_BY,
};
